# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: BuildBlazorWith3d

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Free up Disk Space
        run: |
          echo "=============================================================================="
          echo "Freeing up disk space on CI system"
          echo "=============================================================================="

          echo "Listing 100 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          echo "Removing large packages llvm"
          sudo apt-get remove -y '^llvm-.*'
          echo "Removing large packages php"
          sudo apt-get remove -y 'php.*'
          echo "Removing large packages other"
          sudo apt-get remove -y google-chrome-stable firefox powershell mono-devel
          echo "Removing large packages autoremove"
          sudo apt-get autoremove -y
          echo "Removing large packages clean"
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          # deleting 15GB
          rm -rf /usr/share/dotnet/
          df -h
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100-preview.6.24328.19'
          dotnet-quality: 'preview'

      - name: dotnet tool build generator
        run: dotnet build "src/BlazorWith3d.Unity/BlazorWith3d.Unity.CodeGenerator/BlazorWith3d.Unity.CodeGenerator.csproj" -c Release

      - name: dotnet tool restore
        run: dotnet tool restore

      - name: restore nuget for unity
        run: dotnet nugetforunity restore "samples/BlazorWith3d.ExampleApp.UnityProject"

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: samples/BlazorWith3d.ExampleApp.UnityProject/
          buildsPath: ${{env.DOTNET_ROOT}}/mywebglapp


      - name: Build with dotnet
        run: dotnet build "samples/BlazorWith3d.ExampleApp/BlazorWith3d.ExampleApp.csproj" -c Release

      - name: dotnet publish
        run: dotnet publish "samples/BlazorWith3d.ExampleApp/BlazorWith3d.ExampleApp.csproj" -c Release -f net9.0 -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4716D1A6D8F14733A7DA745162C835C1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F95F3B7058ED412D9ADED69F63293D1B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_295C08DE24C048C7B85515EEA0BECD59 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BlazorWith3d'
          slot-name: 'Production'
          package: .
          